# THIS FILE IS GENERATED BY MACRO
@kwdef struct cleanup_params
i::String = ""
end

#=                     
No description provided.

**Credential required**: *Yes* / **Permission**: *write:admin:drive*
=#
function cleanup(server,params::cleanup_params)
    if params.i == "" && true
        error("/admin/drive/cleanup: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = string("https://",server,"/api","/admin/drive/cleanup")
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

