# THIS FILE IS GENERATED BY MACRO
@kwdef struct files_params
Origin::Union{Nothing, String} = "local"
UserId::Union{Nothing, String} = nothing
SinceId::Union{Nothing, String} = nothing
Hostname::Union{Nothing, String} = nothing
UntilId::Union{Nothing, String} = nothing
Type::Union{Nothing, String} = nothing
Limit::Union{Nothing, Int64} = 10

i::String = ""
end

#=                     
No description provided.

**Credential required**: *Yes* / **Permission**: *read:admin:drive*
=#
function files(server,params::files_params)
    if params.i == "" && true
        error("/admin/drive/files: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = string("https://",server,"/api","/admin/drive/files")
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

