# THIS FILE IS GENERATED BY MACRO
@kwdef struct create_from_public_params
Name::Union{Nothing, String} = nothing
ListId::Union{Nothing, String} = nothing

i::String = ""
end

#=                     
No description provided.

**Credential required**: *Yes* / **Permission**: *write:account*
=#
function create_from_public(params::create_from_public_params)
    if params.i == "" && true
        error("/users/lists/create-from-public: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = "https://misskey.io/api/users/lists/create-from-public"
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

