# THIS FILE IS GENERATED BY MACRO
@kwdef struct push_params
UserId::Union{Nothing, String} = nothing
ListId::Union{Nothing, String} = nothing

i::String = ""
end

#=                     
Add a user to an existing list.

**Credential required**: *Yes* / **Permission**: *write:account*
=#
function push(server,params::push_params)
    if params.i == "" && true
        error("/users/lists/push: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = string("https://",server,"/api","/users/lists/push")
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

