# THIS FILE IS GENERATED BY MACRO
@kwdef struct test_notification_params
i::String = ""
end

#=                     
No description provided.

**Credential required**: *Yes* / **Permission**: *write:notifications*
=#
function test_notification(server,params::test_notification_params)
    if params.i == "" && true
        error("/notifications/test-notification: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = string("https://",server,"/api","/notifications/test-notification")
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

