# THIS FILE IS GENERATED BY MACRO
@kwdef struct my_favorites_params
i::String = ""
end

#=                     
No description provided.

**Credential required**: *Yes* / **Permission**: *read:channels*
=#
function my_favorites(server,params::my_favorites_params)
    if params.i == "" && true
        error("/channels/my-favorites: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = string("https://",server,"/api","/channels/my-favorites")
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

