# THIS FILE IS GENERATED BY MACRO
@kwdef struct update_instance_params
IsSuspended::Union{Nothing, Bool} = nothing
Host::Union{Nothing, String} = nothing

i::String = ""
end

#=                     
No description provided.

**Credential required**: *Yes* / **Permission**: *write:admin:federation*
=#
function update_instance(server,params::update_instance_params)
    if params.i == "" && true
        error("/admin/federation/update-instance: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = string("https://",server,"/api","/admin/federation/update-instance")
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

