# THIS FILE IS GENERATED BY MACRO
@kwdef struct ranking_params
GameMode::Union{Nothing, String} = nothing

i::String = ""
end

#=                     
No description provided.

**Credential required**: *No*
=#
function ranking(server,params::ranking_params)
    if params.i == "" && false
        error("/bubble-game/ranking: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = string("https://",server,"/api","/bubble-game/ranking")
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

