# THIS FILE IS GENERATED BY MACRO
@kwdef struct search_params
UserId::Union{Nothing, String} = nothing
Host::Union{Nothing, String} = nothing
ChannelId::Union{Nothing, String} = nothing
SinceId::Union{Nothing, String} = nothing
Offset::Union{Nothing, Int64} = 0
UntilId::Union{Nothing, String} = nothing
Query::Union{Nothing, String} = nothing
Limit::Union{Nothing, Int64} = 10

i::String = ""
end

#=                     
No description provided.

**Credential required**: *No*
=#
function search(server,params::search_params)
    if params.i == "" && false
        error("/notes/search: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = string("https://",server,"/api","/notes/search")
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

