# THIS FILE IS GENERATED BY MACRO
@kwdef struct change_password_params
Token::Union{Nothing, String} = nothing
NewPassword::Union{Nothing, String} = nothing
CurrentPassword::Union{Nothing, String} = nothing

i::String = ""
end

#=                     
No description provided.

**Internal Endpoint**: This endpoint is an API for the misskey mainframe and is not intended for use by third parties.
**Credential required**: *Yes*
=#
function change_password(params::change_password_params)
    if params.i == "" && true
        error("/i/change-password: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = "https://misskey.io/api/i/change-password"
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

