# THIS FILE IS GENERATED BY MACRO
@kwdef struct get_index_stats_params
i::String = ""
end

#=                     
No description provided.

**Credential required**: *Yes* / **Permission**: *read:admin:index-stats*
=#
function get_index_stats(params::get_index_stats_params)
    if params.i == "" && true
        error("/admin/get-index-stats: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = "https://misskey.io/api/admin/get-index-stats"
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

