# THIS FILE IS GENERATED BY MACRO
@kwdef struct get_user_ips_params
UserId::Union{Nothing, String} = nothing

i::String = ""
end

#=                     
No description provided.

**Credential required**: *Yes* / **Permission**: *read:admin:user-ips*
=#
function get_user_ips(server,params::get_user_ips_params)
    if params.i == "" && true
        error("/admin/get-user-ips: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = string("https://",server,"/api","/admin/get-user-ips")
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

