# THIS FILE IS GENERATED BY MACRO
@kwdef struct unset_user_banner_params
UserId::Union{Nothing, String} = nothing

i::String = ""
end

#=                     
No description provided.

**Credential required**: *Yes* / **Permission**: *write:admin:unset-user-banner*
=#
function unset_user_banner(server,params::unset_user_banner_params)
    if params.i == "" && true
        error("/admin/unset-user-banner: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = string("https://",server,"/api","/admin/unset-user-banner")
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

