# THIS FILE IS GENERATED BY MACRO
@kwdef struct unsuspend_user_params
UserId::Union{Nothing, String} = nothing

i::String = ""
end

#=                     
No description provided.

**Credential required**: *Yes* / **Permission**: *write:admin:unsuspend-user*
=#
function unsuspend_user(params::unsuspend_user_params)
    if params.i == "" && true
        error("/admin/unsuspend-user: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = "https://misskey.io/api/admin/unsuspend-user"
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

