# THIS FILE IS GENERATED BY MACRO
@kwdef struct update_user_note_params
UserId::Union{Nothing, String} = nothing
Text::Union{Nothing, String} = nothing

i::String = ""
end

#=                     
No description provided.

**Credential required**: *Yes* / **Permission**: *write:admin:user-note*
=#
function update_user_note(server,params::update_user_note_params)
    if params.i == "" && true
        error("/admin/update-user-note: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = string("https://",server,"/api","/admin/update-user-note")
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

