# THIS FILE IS GENERATED BY MACRO
@kwdef struct create_params
Password::Union{Nothing, String} = nothing
Username::Union{Nothing, String} = nothing

i::String = ""
end

#=                     
No description provided.

**Credential required**: *No*
=#
function create(server,params::create_params)
    if params.i == "" && false
        error("/admin/accounts/create: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = string("https://",server,"/api","/admin/accounts/create")
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

