# THIS FILE IS GENERATED BY MACRO
@kwdef struct fetch_rss_params
Url::Union{Nothing, String} = nothing

i::String = ""
end

#=                     
No description provided.

**Credential required**: *No*
=#
function fetch_rss(server,params::fetch_rss_params)
    if params.i == "" && false
        error("/fetch-rss: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = string("https://",server,"/api","/fetch-rss")
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

