# THIS FILE IS GENERATED BY MACRO
@kwdef struct fetch_external_resources_params
Hash::Union{Nothing, String} = nothing
Url::Union{Nothing, String} = nothing

i::String = ""
end

#=                     
No description provided.

**Internal Endpoint**: This endpoint is an API for the misskey mainframe and is not intended for use by third parties.
**Credential required**: *Yes*
=#
function fetch_external_resources(server,params::fetch_external_resources_params)
    if params.i == "" && true
        error("/fetch-external-resources: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = string("https://",server,"/api","/fetch-external-resources")
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

