# THIS FILE IS GENERATED BY MACRO
@kwdef struct meta_params
Detail::Union{Nothing, Bool} = true

i::String = ""
end

#=                     
No description provided.

**Credential required**: *No*
=#
function meta(params::meta_params)
    if params.i == "" && false
        error("/meta: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = "https://misskey.io/api/meta"
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

