# THIS FILE IS GENERATED BY MACRO
@kwdef struct reset_password_params
Token::Union{Nothing, String} = nothing
Password::Union{Nothing, String} = nothing

i::String = ""
end

#=                     
Complete the password reset that was previously requested.

**Credential required**: *No*
=#
function reset_password(server,params::reset_password_params)
    if params.i == "" && false
        error("/reset-password: This function require credential")
    end
    header = Dict("Content-Type" => "application/json")
    url = string("https://",server,"/api","/reset-password")
    params = Dict(lowercasefirst(string(key)) => getfield(params, key) for key in propertynames(params)) |> x -> filter(t -> t.second != nothing,x) |> JSON.json
    request = HTTP.post(url, header, params)
    request.body |> String |> JSON.parse
end

